name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECT_API_BUILD: './src/Milochau.Core.Aws.sln'
  PROJECT_API_TESTS: './src/Milochau.Core.Aws.sln'
  DOTNET_VERSION: 7.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  VERBOSITY: normal

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build libraries
        uses: amilochau/github-actions/build/netcore@v4
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          projectsToBuild: ${{ env.PROJECT_API_BUILD }}
          projectsToTest: ${{ env.PROJECT_API_TESTS }}
