name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECT_API_BUILD: './src/Milochau.Core.Aws.sln'
  PROJECT_API_TESTS: './src/Milochau.Core.Aws.sln'
  DOTNET_VERSION: 9.0.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build libraries
        uses: amilochau/github-actions/build/netcore@v4
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          projectsToBuild: ${{ env.PROJECT_API_BUILD }}
          projectsToTest: ${{ env.PROJECT_API_TESTS }}
      - name: Upload artifact (compressed)
        uses: actions/upload-artifact@v4
        with:
          name: todelete
          path: .
          if-no-files-found: error
          retention-days: 1
