name: Deploy libraries
run-name: Deploy libraries - ${{ github.ref }}

on:
  workflow_dispatch:

concurrency: deploy_libraries

env:
  PROJECTS_BUILD: './src/Milochau.Core.Aws.sln'
  PROJECTS_LIBRARIES: './src/Milochau.Core.Aws.sln'
  VERSION_FILE: './src/Directory.Build.props'
  DOTNET_VERSION: 8.0.x

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy libraries
        uses: amilochau/github-actions/release/nuget@v4
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          projectsToPack: ${{ env.PROJECTS_LIBRARIES }}
          versionFile: ${{ env.VERSION_FILE }}
          nugetOrgToken: ${{ secrets.NUGETORG_TOKEN }}
